=== ffRTwegrFEW555/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xa="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">


    <!--        -->
    <!-- Root   -->
    <!--        -->

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="Group"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>


    <!--        -->
    <!-- User   -->
    <!--        -->

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="email" use="required"/>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
            <xs:attribute type="xs:IDREFS" name="groups"/>
        </xs:complexType>
    </xs:element>


    <!--            -->
    <!-- User flag  -->
    <!--            -->

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>


    <!--        -->
    <!-- City   -->
    <!--        -->

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <!--            -->
    <!-- Project    -->
    <!--            -->

    <xs:element name="Project">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string" />
                <xs:element name="Description" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Group">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:ID" use="required"/>
                    <xs:attribute name="status" type="projectGroupStatus" use="required"/>
                    <xs:attribute name="parent" type="xs:IDREF" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="projectGroupStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== ffRTwegrFEW555/masterjava/src/test/resources/payloadWrong.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com" groups="topjava07 masterjava01">
            <fullName>Full Name</fullName>
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru" groups="topjava07 topjava08 masterjava01">
            <fullName>Admin</fullName>
        </User>
        <User flag="deleted" city="spb" email="mail@yandex.ru" groups="masterjava01">
            <fullNae>Deleted</fullNae>
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project id="topjava">
            <Name>TopJava</Name>
            <Description>Java EE project</Description>
        </Project>
        <Project id="masterjava">
              <Name>MasterJava</Name>
            <Description>Java EE project+</Description>
        </Project>
    </Projects>
    <Groups
